processed 7 tasks

init:
A: object(0,0)

task 1, lines 6-10:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 2, lines 12-42:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 29
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 3, lines 44-48:
//# run-graphql
Response: {
  "data": {}
}

task 4, lines 50-54:
//# run-graphql
Response: {
  "data": {
    "chainIdentifier": "8f58ad28"
  }
}

task 5, lines 56-60:
//# run-graphql
Response: {
  "data": {
    "chainIdentifier": "8f58ad28"
  }
}

task 6, lines 62-66:
//# run-graphql
Response: {
  "data": {}
}
