processed 14 tasks

task 1, lines 6-14:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false
      }
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 3,
      "outputNodes": 3,
      "depth": 3,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 132
    }
  }
}

task 2, lines 16-26:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 80,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 163
    }
  }
}

task 3, lines 28-42:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "transactionBlocks": {
            "edges": [
              {
                "txns": {
                  "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 6,
      "outputNodes": 1640,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 206
    }
  }
}

task 4, lines 44-65:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notOne": {
            "edges": [
              {
                "txns": {
                  "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
                }
              }
            ]
          },
          "isOne": {
            "edges": [
              {
                "txns": {
                  "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 1720,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 306
    }
  }
}

task 5, lines 67-88:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notZero": {
            "edges": [
              {
                "txns": {
                  "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
                }
              }
            ]
          },
          "isZero": {
            "edges": []
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 1640,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 308
    }
  }
}

task 6, lines 90-100:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 145
    }
  }
}

task 7, lines 102-112:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 143
    }
  }
}

task 8, lines 114-142:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3",
            "first": null,
            "last": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 14,
      "outputNodes": 3320,
      "depth": 8,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 501
    }
  }
}

task 9, lines 144-170:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3",
          "first": null,
          "last": null
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 13,
      "outputNodes": 3300,
      "depth": 7,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 533
    }
  }
}

task 10, lines 172-221:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3",
            "a": null,
            "b": null
          }
        }
      ]
    },
    "events": {
      "edges": []
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 24,
      "outputNodes": 86340,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1395
    }
  }
}

task 11, lines 223-248:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "AhErVYcPUpKCUJsiQ2GAtiBZuuo2n3nVYLngQpTiuuQ3",
            "a": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 12,
      "outputNodes": 33300,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 704
    }
  }
}

task 12, lines 250-260:
//# run-graphql --show-usage
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 80,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 154
    }
  },
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 13, lines 262-272:
//# run-graphql --show-usage
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 80,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 147
    }
  },
  "errors": [
    {
      "message": "Invalid value for argument \"first\", expected type \"Int\"",
      "locations": [
        {
          "line": 3,
          "column": 21
        }
      ]
    }
  ]
}
