processed 5 tasks

task 1, lines 6-28:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
      "sequenceNumber": 0
    }
  }
}

task 2, line 30:
//# create-checkpoint
Checkpoint created: 1

task 3, line 33:
//# create-checkpoint
Checkpoint created: 2

task 4, lines 36-58:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "C3gNdxw7tLsULYLt541SEEY2vuyPYBimZwutcY8YQB1a",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "DKLNxHiQP2JHxDHhCSDcDtvBcw6PrCXLVvYB2KVfUctJ",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "C3gNdxw7tLsULYLt541SEEY2vuyPYBimZwutcY8YQB1a",
      "sequenceNumber": 2
    }
  }
}
