processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 12-39:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 41:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 43-45:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: sui::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4, line 47:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 49-90:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 92-133:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 135:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8, line 137:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9, line 139:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 141-194:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 198:
//# create-checkpoint
Checkpoint created: 4

task 14, line 202:
//# create-checkpoint
Checkpoint created: 5

task 16, line 206:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 208-249:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IP43q6a/xEEnB5jyaFdgQnXY2AwarcCwCi7PLI/bRPuIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xfe37aba6bfc441270798f26857604275d8d80c1aadc0b00a2ecf2c8fdb44fb88",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IHm1xv3SSenvmYDQCYNS3g8PPG3cJoIRJjBI2JV09+1sAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x79b5c6fdd249e9ef9980d0098352de0f0f3c6ddc268211263048d89574f7ed6c",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMLizONLkUGpGqbmrvrdiM9clJgJKMh9ST1MfWOYbCcQAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc2e2cce34b9141a91aa6e6aefadd88cf5c94980928c87d493d4c7d63986c2710",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 251:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 253:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 255-284:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
