processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 17-34:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 36-37:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 39:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 41-44:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5, line 46:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 48-52:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7, line 54:
//# create-checkpoint
Checkpoint created: 3

task 9, line 58:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 60-134:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                "value": "6"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                "value": "5"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                "value": "200"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                "value": "2"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                "value": "4"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                "value": "3"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x4f64357f86f4c9e91dd0db4cb27e90913a3a69002b0270404360dd4541f98a5e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 136-180:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x4f64357f86f4c9e91dd0db4cb27e90913a3a69002b0270404360dd4541f98a5e",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x4f64357f86f4c9e91dd0db4cb27e90913a3a69002b0270404360dd4541f98a5e",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x4f64357f86f4c9e91dd0db4cb27e90913a3a69002b0270404360dd4541f98a5e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 182:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 184:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 186-260:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                "value": "6"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                "value": "5"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                "value": "200"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                "value": "2"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                "value": "4"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                "value": "3"
              },
              "type": {
                "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x4f64357f86f4c9e91dd0db4cb27e90913a3a69002b0270404360dd4541f98a5e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 262:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 264-299:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0adc35c5da6cf1b4f90395fbad3014e1fbf0340a072964d3e9d4fd267fbbff14",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4643058893bba48ddd24f496631d70b65b9fb06073e40e931054551e278273cf",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x55681d04f40782bef733b12b82f1f02170f6455d3016dde9762174db8a510830",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5fcd6fc6f73a3b3031c7d5143d01834a9fdc1b20154d4103441191efc51fd79d",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc8879d0ef952a3d230d87f12496c2adbf901f4e2722eb0f6826f8762852ae84c",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xde4451754a98759de3114961b722189bbd2d4bd9158ce161bb604c6996bfd17a",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7f55ca07a125dd5bd2a5e4a5eaa09aef1ccb3e6e56efdb44d55f8098a60956d8::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
