processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-26:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4, line 32:
//# run Test::M1::create --args 0 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, line 34:
//# run Test::M1::create --args 0 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6, line 36:
//# create-checkpoint
Checkpoint created: 1

task 7, line 38:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8, line 40:
//# run Test::M1::create --args 0 @A --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9, line 42:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10, line 44:
//# create-checkpoint
Checkpoint created: 2

task 11, line 46:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12, line 48:
//# run Test::M1::create --args 0 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13, line 50:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 52-76:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJ0YyI6MX0",
                "node": {
                  "digest": "Ap9FiJGfZ2hbKbbYiWvKCqUriZh51TuaLqavgM9eafD7",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJ0YyI6MX0",
                "node": {
                  "digest": "8FGXx3CxjRxi7xV2d6R2FsiyrsyiBfiHLPyGtVtZodES",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJ0YyI6MX0",
                "node": {
                  "digest": "HsVHTLTZk5EPHudApRULZfARE7CpCjMsuAPd1UeC6QiP",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJ0YyI6MX0",
                "node": {
                  "digest": "qMEs41Xi9K7Nae7AxdnJT9d82EYYDvyk9KDixC8ktt3",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJ0YyI6Mn0",
                "node": {
                  "digest": "9k4rfA8ZMvyvsU6ar3DVBHH928Tw2aKorQCGJKNCUnYb",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJ0YyI6Mn0",
                "node": {
                  "digest": "GLiUrKx2gJVwbRaMtGwVX26PPyhtUbknb3Q9pa3c9XbQ",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJ0YyI6Mn0",
                "node": {
                  "digest": "9w6r3o2uCzXjbktKREZJSkAFcAH3uKjNFPCTS1qasXKD",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJ0YyI6M30",
                "node": {
                  "digest": "12ZTS2Sz3L1HkXMbDsUnfBZHX7XqgtB4KYwNcXfJ2WfS",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwidGMiOjN9",
                "node": {
                  "digest": "5cHBxf8yer7uxaGUR1H3X3zHFvqTHgW3fp298CRFdxL",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INZniY4QS/3KTPQmfQkXW+1ZEk7bT4cRwgbiMhUcllEXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15, lines 78-95:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
