processed 14 tasks

task 1, lines 6-19:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 21:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3, line 23:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4, line 25:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, line 27:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6, line 29:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7, line 31:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 33-43:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAMePMPOFpzY1IhbjiIiR5GHGkDqH4lvxSEJVZCkvtU7AQAAAAAAAAA="
          },
          {
            "cursor": "IECijfeVROwCM/8FWCiVoroEXZe9gX7GjoLGsJgjdJzvAQAAAAAAAAA="
          },
          {
            "cursor": "IFAEpxUcBPE8F5z5yWlitHaYI2rliiS7w9fFhXssDaCpAQAAAAAAAAA="
          },
          {
            "cursor": "IIqj/uDYsk1nEFODJBankuUXWrmCfKgDvU2P0GvVfnWmAQAAAAAAAAA="
          },
          {
            "cursor": "IIvXcDAQ5RgKZu6eVQmb/412/LLX5dHwEFLgG2PJVptzAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 45-55:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAMePMPOFpzY1IhbjiIiR5GHGkDqH4lvxSEJVZCkvtU7AQAAAAAAAAA="
          },
          {
            "cursor": "IECijfeVROwCM/8FWCiVoroEXZe9gX7GjoLGsJgjdJzvAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 57-69:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IFAEpxUcBPE8F5z5yWlitHaYI2rliiS7w9fFhXssDaCpAQAAAAAAAAA="
          },
          {
            "cursor": "IIqj/uDYsk1nEFODJBankuUXWrmCfKgDvU2P0GvVfnWmAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 11, lines 71-81:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IIvXcDAQ5RgKZu6eVQmb/412/LLX5dHwEFLgG2PJVptzAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 83-93:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 13, lines 95-104:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IIqj/uDYsk1nEFODJBankuUXWrmCfKgDvU2P0GvVfnWmAQAAAAAAAAA="
          },
          {
            "cursor": "IIvXcDAQ5RgKZu6eVQmb/412/LLX5dHwEFLgG2PJVptzAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}
